locals {
  subscriptions_schema = [
    { name = "id", type = "STRING", mode = "NULLABLE" },
    { name = "object", type = "STRING", mode = "NULLABLE" },
    { name = "application", type = "STRING", mode = "NULLABLE" },
    { name = "application_fee_percent", type = "STRING", mode = "NULLABLE" },
    { name = "billing_cycle_anchor", type = "INTEGER", mode = "NULLABLE" },
    { name = "billing_cycle_anchor_config", type = "STRING", mode = "NULLABLE" },
    { name = "billing_thresholds", type = "STRING", mode = "NULLABLE" },
    { name = "cancel_at", type = "INTEGER", mode = "NULLABLE" },
    { name = "cancel_at_period_end", type = "BOOLEAN", mode = "NULLABLE" },
    { name = "canceled_at", type = "INTEGER", mode = "NULLABLE" },
    { name = "collection_method", type = "STRING", mode = "NULLABLE" },
    { name = "created", type = "INTEGER", mode = "NULLABLE" },
    { name = "currency", type = "STRING", mode = "NULLABLE" },
    { name = "current_period_end", type = "INTEGER", mode = "NULLABLE" },
    { name = "current_period_start", type = "INTEGER", mode = "NULLABLE" },
    { name = "customer", type = "STRING", mode = "NULLABLE" },
    { name = "days_until_due", type = "STRING", mode = "NULLABLE" },
    { name = "default_payment_method", type = "STRING", mode = "NULLABLE" },
    { name = "default_source", type = "STRING", mode = "NULLABLE" },
    { name = "description", type = "STRING", mode = "NULLABLE" },
    { name = "discount", type = "STRING", mode = "NULLABLE" },
    { name = "discounts", type = "JSON", mode = "NULLABLE" },
    { name = "ended_at", type = "STRING", mode = "NULLABLE" },
    { name = "latest_invoice", type = "STRING", mode = "NULLABLE" },
    { name = "livemode", type = "BOOLEAN", mode = "NULLABLE" },
    { name = "next_pending_invoice_item_invoice", type = "STRING", mode = "NULLABLE" },
    { name = "on_behalf_of", type = "STRING", mode = "NULLABLE" },
    { name = "pause_collection", type = "STRING", mode = "NULLABLE" },
    { name = "pending_invoice_item_interval", type = "STRING", mode = "NULLABLE" },
    { name = "pending_setup_intent", type = "STRING", mode = "NULLABLE" },
    { name = "pending_update", type = "STRING", mode = "NULLABLE" },
    { name = "quantity", type = "FLOAT", mode = "NULLABLE" },
    { name = "schedule", type = "STRING", mode = "NULLABLE" },
    { name = "start_date", type = "INTEGER", mode = "NULLABLE" },
    { name = "status", type = "STRING", mode = "NULLABLE" },
    { name = "test_clock", type = "STRING", mode = "NULLABLE" },
    { name = "transfer_data", type = "STRING", mode = "NULLABLE" },
    { name = "trial_end", type = "STRING", mode = "NULLABLE" },
    { name = "trial_start", type = "STRING", mode = "NULLABLE" },
    { name = "automatic_tax.enabled", type = "BOOLEAN", mode = "NULLABLE" },
    { name = "automatic_tax.liability", type = "STRING", mode = "NULLABLE" },
    { name = "cancellation_details.comment", type = "STRING", mode = "NULLABLE" },
    { name = "cancellation_details.feedback", type = "STRING", mode = "NULLABLE" },
    { name = "cancellation_details.reason", type = "STRING", mode = "NULLABLE" },
    { name = "invoice_settings.account_tax_ids", type = "STRING", mode = "NULLABLE" },
    { name = "invoice_settings.issuer.type", type = "STRING", mode = "NULLABLE" },
    { name = "items.object", type = "STRING", mode = "NULLABLE" },
    { name = "items.data", type = "JSON", mode = "NULLABLE" },
    { name = "items.has_more", type = "BOOLEAN", mode = "NULLABLE" },
    { name = "items.total_count", type = "INTEGER", mode = "NULLABLE" },
    { name = "items.url", type = "STRING", mode = "NULLABLE" },
    { name = "payment_settings.payment_method_options", type = "STRING", mode = "NULLABLE" },
    { name = "payment_settings.payment_method_types", type = "STRING", mode = "NULLABLE" },
    { name = "payment_settings.save_default_payment_method", type = "STRING", mode = "NULLABLE" },
    { name = "plan.id", type = "STRING", mode = "NULLABLE" },
    { name = "plan.object", type = "STRING", mode = "NULLABLE" },
    { name = "plan.active", type = "BOOLEAN", mode = "NULLABLE" },
    { name = "plan.aggregate_usage", type = "STRING", mode = "NULLABLE" },
    { name = "plan.amount", type = "FLOAT", mode = "NULLABLE" },
    { name = "plan.amount_decimal", type = "STRING", mode = "NULLABLE" },
    { name = "plan.billing_scheme", type = "STRING", mode = "NULLABLE" },
    { name = "plan.created", type = "INTEGER", mode = "NULLABLE" },
    { name = "plan.currency", type = "STRING", mode = "NULLABLE" },
    { name = "plan.interval", type = "STRING", mode = "NULLABLE" },
    { name = "plan.interval_count", type = "FLOAT", mode = "NULLABLE" },
    { name = "plan.livemode", type = "BOOLEAN", mode = "NULLABLE" },
    { name = "plan.meter", type = "STRING", mode = "NULLABLE" },
    { name = "plan.nickname", type = "STRING", mode = "NULLABLE" },
    { name = "plan.product", type = "STRING", mode = "NULLABLE" },
    { name = "plan.tiers_mode", type = "STRING", mode = "NULLABLE" },
    { name = "plan.transform_usage", type = "STRING", mode = "NULLABLE" },
    { name = "plan.trial_period_days", type = "STRING", mode = "NULLABLE" },
    { name = "plan.usage_type", type = "STRING", mode = "NULLABLE" },
    { name = "trial_settings.end_behavior.missing_payment_method", type = "STRING", mode = "NULLABLE" },
    { name = "automatic_tax.liability.type", type = "STRING", mode = "NULLABLE" },
    { name = "payment_settings.payment_method_options.acss_debit", type = "STRING", mode = "NULLABLE" },
    { name = "payment_settings.payment_method_options.bancontact", type = "STRING", mode = "NULLABLE" },
    { name = "payment_settings.payment_method_options.card.network", type = "STRING", mode = "NULLABLE" },
    { name = "payment_settings.payment_method_options.card.request_three_d_secure", type = "STRING", mode = "NULLABLE" },
    { name = "payment_settings.payment_method_options.customer_balance", type = "STRING", mode = "NULLABLE" },
    { name = "payment_settings.payment_method_options.konbini", type = "STRING", mode = "NULLABLE" },
    { name = "payment_settings.payment_method_options.sepa_debit", type = "STRING", mode = "NULLABLE" },
    { name = "payment_settings.payment_method_options.us_bank_account", type = "STRING", mode = "NULLABLE" },
    { name = "metadata.customer_id", type = "STRING", mode = "NULLABLE" },
    { name = "metadata.deal_id", type = "STRING", mode = "NULLABLE" },
    { name = "metadata.product_id", type = "STRING", mode = "NULLABLE" },
    { name = "metadata.stripe_payment_link_id", type = "STRING", mode = "NULLABLE" },
    { name = "metadata.student_id", type = "STRING", mode = "NULLABLE" },
    { name = "plan", type = "STRING", mode = "NULLABLE" },
    { name = "pause_collection.behavior", type = "STRING", mode = "NULLABLE" },
    { name = "pause_collection.resumes_at", type = "STRING", mode = "NULLABLE" }
  ]
}

variable "tables" {
  default = [
    {
      table_name = "subscriptions"
      schema     = local.subscriptions_schema
    }
  ]
}
